"""Redesign family members schema.

Revision ID: a973d5cbbdd8
Revises: 621ea46368cb
Create Date: 2026-08-17 16:11:09.660604

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a973d5cbbdd8'
down_revision: str | Sequence[str] | None = '621ea46368cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'family_members',
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        'family_members', sa.Column('date_of_birth', sa.Date(), nullable=True)
    )
    op.add_column(
        'family_members',
        sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column('family_members', 'calendar_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'family_members',
        sa.Column('calendar_id', sa.VARCHAR(), nullable=False),
    )
    op.drop_column('family_members', 'relation')
    op.drop_column('family_members', 'date_of_birth')
    op.drop_column('family_members', 'email')
    # ### end Alembic commands ###
