"""chores_redesign_add_associations_and_recurrence_rules

Revision ID: f39bfa5aac9f
Revises: b3e7f2a19c45
Create Date: 2026-08-26 19:03:59.091197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f39bfa5aac9f'
down_revision: Union[str, Sequence[str], None] = 'b3e7f2a19c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create associations table
    op.create_table('chore_associations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('master_chore_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_open_pool', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_chore_id'], ['master_chores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Update chore_instances - use batch mode for SQLite
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('association_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_instance_association', 'chore_associations', ['association_id'], ['id'])
        batch_op.drop_column('signed_off_at')
        batch_op.drop_column('signoff_by')
    
    # Update master_chores - use batch mode for SQLite
    with op.batch_alter_table('master_chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_rule', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('max_occurrences', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occurrence_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('conditions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_collaborative', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.drop_column('frequency')
        batch_op.drop_column('approved_by')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_chores', sa.Column('approved_by', sa.VARCHAR(), nullable=True))
    op.add_column('master_chores', sa.Column('frequency', sa.VARCHAR(), nullable=False))
    op.drop_column('master_chores', 'is_collaborative')
    op.drop_column('master_chores', 'conditions')
    op.drop_column('master_chores', 'occurrence_count')
    op.drop_column('master_chores', 'max_occurrences')
    op.drop_column('master_chores', 'end_date')
    op.drop_column('master_chores', 'recurrence_rule')
    op.add_column('chore_instances', sa.Column('signoff_by', sa.VARCHAR(), nullable=True))
    op.add_column('chore_instances', sa.Column('signed_off_at', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'chore_instances', type_='foreignkey')
    op.drop_column('chore_instances', 'association_id')
    op.drop_table('chore_associations')
    # ### end Alembic commands ###
